In [1]:
x=int(input("Enter a number:"))
y=int(input("Enter second number:"))
if(x==45):
    print("Its 45")
else:
    print(x+y)

Enter a number:45
Enter second number:45
Its 45


In [3]:
x=10

In [4]:
type(x)

int

In [6]:
p=[10,12,14,16,18]
p


[10, 12, 14, 16, 18]

In [7]:
p.insert(2,25)

In [8]:
p


[10, 12, 25, 14, 16, 18]

In [9]:
y=[10,2,3,4,5,6,[4,5,6,],7]

In [10]:
y


[10, 2, 3, 4, 5, 6, [4, 5, 6], 7]

In [11]:
d2={12:"hello",(1,2,3,4):[4,5,6,7]}

In [12]:

d2[12]

'hello'

In [13]:
x=input("enter the username:")
y=input("enter the password:")
if(x=='dikshant') and (y=='dikshant'):
  print("successful")
else:
  print("Try again")

enter the username:dikshant
enter the password:dikshant
successful


In [14]:
x=input("enter the username:")
if(x=='dikshant'):
  y=input("enter the password:")
  if(y=="dikshant"):
    print("welcome")
  else:
    print("Try again")


enter the username:dikshant
enter the password:dikshant
welcome


In [15]:
for i in range(1,10,2):
  print(i)

1
3
5
7
9


In [16]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [18]:
l=['dikshant','mayank','abbas']
for i in range(len(l)):
  print(i)

0
1
2


In [19]:
s=[]
l=['dikshant','mayank','abbas']
for i in l:
  print(str(len(i)),":",i)
  s.append(len(i))
print(s)

8 : dikshant
6 : mayank
5 : abbas
[8, 6, 5]


In [20]:
def name():
  print('dikshant')

In [21]:
name()

dikshant


In [24]:
def name(x):
  print("dikshant and",x)
name('mayank')
name('abbas')

dikshant and mayank
dikshant and abbas


In [26]:
import numpy as np 

In [27]:
x=np.array([10,11,12,13])
print(x)

[10 11 12 13]


In [29]:
x=np.array([[10,11,12,13],[14,15,16,17]])
print(x)

[[10 11 12 13]
 [14 15 16 17]]


In [31]:
x=np.array([[10,11,12,13],[14,15,16,17],[18,19,20,21]])
print(x.ndim)

2


In [33]:
print(x)
print(x.sum())
#print(x.prod())
print(x.max())
print(x.min())
print(x.argmax())
print(x.argmin())

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
186
21
10
11
0


In [34]:
x[0,0]

10

In [35]:
y=x[:,-1:]
y

array([[13],
       [17],
       [21]])

In [36]:
x.shape

(3, 4)

In [37]:
b=x.reshape(4,3)

In [38]:
x.transpose()

array([[10, 14, 18],
       [11, 15, 19],
       [12, 16, 20],
       [13, 17, 21]])

In [40]:
a=0
a=np.arange(16).reshape(4,4)

In [41]:
a[1:3,:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
a[1:3,2:]

array([[ 6,  7],
       [10, 11]])

In [43]:
a=np.arange(18).reshape(3,3,2)

In [44]:
a


array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])